stellar/helm-charts

charts/anchor-platform/sep-service/Chart.yaml
charts/anchor-platform/sep-service/templates/deployment.yaml
charts/anchor-platform/sep-service/values.yaml

* Expose the `8082` metrics port to the internal network.
* Add `deployment.annotations` to the example values.
* Delete duplicate appearance of `ORG_URL` in the example values.
To improve the helm chart to be closer to a real-world scenario.

Feature: update helm chart by exposing the metrics port to the internal network

---

charts/anchor-platform/sep-service/Chart.yaml
charts/anchor-platform/sep-service/templates/deployment.yaml
charts/anchor-platform/sep-service/templates/ingress.yaml
charts/anchor-platform/sep-service/templates/service.yaml
charts/anchor-platform/sep-service/values.yaml

Add an option to make the Stellar observer into a separate deployment service.
Because it's recommended to use it as a separate service.
Same as https://github.com/stellar/java-stellar-anchor-sdk/pull/613.

Feature: separate observer deployment

---

charts/horizon/README.md
charts/horizon/templates/horizon-web-deployment.yaml
charts/horizon/values.yaml

The default values.yaml file did not contain example annotations. This PR fixes that
This will make it easier to deploy the chart and see what values are supported

Improve horizon chart values.yaml

---

charts/horizon/Chart.yaml
charts/horizon/templates/_helpers.tpl
charts/horizon/templates/horizon-ingest-sts.yaml
charts/horizon/templates/horizon-web-deployment.yaml
charts/horizon/values.yaml

* add support for setting arbitrary labels to the horizon chart
* add horizon_network label to Deployment and StatefulSet templates
* allow custom network with any name
Those changes will give us more control over labels

horizon: add arbitrary label support

---

charts/core/README.md
charts/core/futurenet-values.yaml

Add futurenet config to Core helm chart
We need a sample config file in core helm chart for the watcher.

Add futurenet config to Core helm chart

---

charts/core/templates/_helpers.tpl
charts/core/templates/core-sts.yaml
charts/core/templates/history-proxy.yaml
charts/core/values.yaml

Add history proxy support to the core chart
This is required for validator nodes

Add history proxy support to the core chart

---

charts/soroban-rpc/Chart.yaml
charts/soroban-rpc/README.md
charts/soroban-rpc/templates/soroban-rpc-cm.yaml
charts/soroban-rpc/templates/soroban-rpc-sts.yaml
charts/soroban-rpc/values.yaml

This PR refactors the soroban-rpc chart. Summary of changes made:
* updated default docker registry to the official stellar registry
* removed stellar core subchart since we don't use it any more
* moved core settings one level up in the values file
* updated core settings to match latest recommended values
* soroban-rpc now accepts config file. Moved config to ConfigMap
* soroban-rpc doesn't support HA yet, harcoded replicas at 1 to avoid mistakes
* moved from Deployment to StatefulSet. Split templates into multiple files
* added persistence support
* bumped appVersion to latest preview release of soroban
Soroban-rpc now comes with core bundled and the chart has to be updated to match that.

Refactor soroban-rpc chart

---

charts/soroban-rpc/Chart.yaml
charts/soroban-rpc/templates/soroban-rpc-sts.yaml
charts/soroban-rpc/values.yaml

Temporarily hide persistenct support in the soroban-rpc chart.
Persistence is not fully tested at this stage so we'd like it to be less visible at this stage.

soroban-rpc: disable persistence support

---

charts/anchor-platform/sep-service/Chart.yaml
charts/anchor-platform/sep-service/templates/deployment.yaml

This PR fixes the metrics port for the stellar observer services to 18083 since this port is currently hardcoded in the application for now.   This will be released as stellar/sep chart version 0.3.96

ANCHOR-408 helm-charts/sep-service observer port is fixed

---

charts/anchor-platform/sep-service/Chart.yaml
charts/anchor-platform/sep-service/templates/deployment.yaml

This PR patches an error in the anchor-platform helm chart.  In the stellar observer service, the deployment templates path for pulling annotations from the values file currently pulls those annotations from the sep service values.  This PR patches this error by using annotations from the stellarObserver.deployment values.   This enables you to configure different annotations for both sep service and observer service.  This has been tested using helm-template and deploying the helm chart into a local k8 cluster.

ANCHOR-403 fix observer deployment annotations

---

charts/soroban-rpc/Chart.yaml

* remove beta from the chart version
* bump appVersion to latest soroban-rpc release
This will remove the need to use `--devel` flag during deployments using helm install

Bump soroban-rpc chart version and appVersion

---

charts/horizon/Chart.yaml
charts/horizon/templates/horizon-ingest-cm.yaml
charts/horizon/values.yaml

include the APPLY_MIGRATIONS config flag in ingest configmap for cases where users know they way this feature, it's disabled by default.

added horizon apply migrations flag

---

charts/soroban-rpc/Chart.yaml
charts/soroban-rpc/templates/soroban-rpc-cm.yaml
charts/soroban-rpc/testnet-values.yaml
charts/soroban-rpc/values.yaml

the rpc chart should expose the diagnostic events captive core config as a values.yml option.

include diagnostic events as values config

---

charts/soroban-rpc/Chart.yaml
charts/soroban-rpc/templates/soroban-rpc-cm.yaml
charts/soroban-rpc/templates/soroban-rpc-sts.yaml

Add soroban-rpc readiness probe
This will ensure pods are not sent requests until they are ready to handle them correctly.

Add soroban-rpc readiness probe

---

charts/soroban-rpc/templates/soroban-rpc-sts.yaml

Update the rpc chart to include an updates of the statefulset that assist for better zero downtime of rpc at runtime and upgrade time:
* default the sts to replicas=2, this will help ensure zero downtime during upgrades, as the sts controller can always keep one replica pod up while it updates the other, as updating a pod requires restart, which also incurs a captive core catchup/sync which can be significant time that the instance is not passing readiness during that startup time.
* leverage new rpc health status info to verify `retention window fully populated` condition into the readiness probe check 
These changes have been verified on cluster deployments using the same changes directly through k8s manifests:
https://github.com/stellar/kube/pull/2098
Closes #82

Update RPC chart to use additional zero downtime mechanisms

---

charts/stellar-disbursement-platform/Chart.yaml
charts/stellar-disbursement-platform/minimal-values.yaml
charts/stellar-disbursement-platform/templates/05.1-secrets-sdp.yaml
charts/stellar-disbursement-platform/templates/05.2-secrets-ap.yaml
charts/stellar-disbursement-platform/templates/05.3-secrets-tss.yaml

* Small fixes when running this Chart using the minimal-values.yaml
* Changed default background job processing to `Scheduler` instead of `Kafka` for an easier minimal setup
* Fixed Anchor secrets that were being generated from the ConfigMap 
1. Pre-requisites
1. `docker desktop` 
2. `kubectl`  in command line 
3. `helm` in command line 
2. Enable Kubernetes in docker-desktop settings 
3. Switch to `docker-desktop` kubernetes context 
```
kubectl config use-context docker-desktop
```
4. Install the Stellar helm chart
* Add the Stellar helm repository
```
helm repo add stellar https://helm.stellar.org/charts
```
* Copy minimal values 
```
curl -LJO https://raw.githubusercontent.com/stellar/stellar-disbursement-platform-backend/develop/helmchart/sdp/minimal-values.yaml
```
* Customize …

[SDP-1236] Fix SDP helm chart defaults and minimal-values

---

charts/stellar-disbursement-platform/Chart.yaml
charts/stellar-disbursement-platform/values.yaml

This issue is encountered by the UNICC - because of a different post render validation used by flux 
https://github.com/fluxcd/helm-controller/issues/283
This was the way to reproduce the issue using kustomize. 
```
cat > kustomize.sh <<\EOT
#!/bin/bash
cat - > helm-generated-output.yaml
kustomize build . && rm helm-generated-output.yaml
EOT
chmod +x kustomize.sh
cat > kustomization.yaml <<\EOT
resources:
- helm-generated-output.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches: []
EOT
``` 
```
helm template sdp . --post-renderer ./kustomize.sh -f myvalues.yaml
```
```
Error: error while running post render on files: error while running command /Users/.../dev/helm-charts/charts/stellar-disbursement-platform/kustomize.sh. error output:
Error: map[string]interface …
```

SDP-1280 Fix duplicate base_url in SDP helm chart

---

charts/stellar-disbursement-platform/Chart.yaml
charts/stellar-disbursement-platform/templates/01.2-configmap-ap.yaml

It's looking like that value for anchor is `PUBLIC` not `PUBNET` https://github.com/stellar/java-stellar-anchor-sdk/blob/0d81cff3fd00a90114ac2a758ea37aea0528a5e5/platform/src/main/java/org/stellar/anchor/platform/config/PropertyAppConfig.java#L93

Change Pubnet config to `PUBLIC` for SDP

---

charts/horizon/templates/_helpers.tpl
charts/horizon/templates/core-configmap.yaml
charts/horizon/templates/ingest-configmap.yaml
charts/horizon/templates/ingest-statefulset.yaml
charts/horizon/templates/ingress.yaml
charts/horizon/templates/web-configmap.yaml
charts/horizon/templates/web-deployment.yaml

This PR cleans up some templating and indentation in the horizon chart
- use helm native `include` that returns a string over the go template `template` function
- align the indentation of the templating functions to where the resource values will be
- remove unused if function for service account
- fix indentation to match other values

Clean up tempalting and indenting in horizon chart

---

charts/horizon/templates/core-configmap.yaml
charts/horizon/templates/ingest-core-service.yaml
charts/horizon/templates/ingest-ingress.yaml
charts/horizon/templates/ingest-service.yaml
charts/horizon/templates/ingest-statefulset.yaml
charts/horizon/templates/web-deployment.yaml
charts/horizon/templates/web-ingress.yaml
charts/horizon/templates/web-service.yaml

This PR breaks the horizon resources into separate templates
Currently the chart has some collections of resources in files that either dont indicate that those resources are there or it is not the most natural collection
This makes it so that each resource is in its own file

Break horizon resources into separate files

---

charts/stellar-disbursement-platform/Chart.yaml
charts/stellar-disbursement-platform/templates/04.1-ingress-sdp.yaml
charts/stellar-disbursement-platform/templates/04.2-ingress-ap.yaml

Remove `nginx.ingress.kubernetes.io/server-snippet` annotation
[This snippet](https://github.com/stellar/stellar-disbursement-platform-backend/pull/5/files#diff-ee6d3e08fc06195d14f677988de28e706e50231a869f86bbd8aa3110edc3d816) was a way to expose only one toml file (the AP one) through the same ingress, since we were using only one ingress for both SDP and AP.
It doesn't make sense anymore and should be removed

SDP 3.1.1: remove nginx.ingress.kubernetes.io/server-snippet annotation

---

charts/horizon/templates/ingest-statefulset.yaml
charts/horizon/templates/ingest.yaml
charts/horizon/values.yaml

horizon-ingest: offer a choice between Statefulset and Deployment
Deployment for single pods
I tested both options with `helm template` and verified they work  in `dev-eks`
the template is updated
https://github.com/stellar/ops/issues/3821

horizon-ingest: offer choice between Deployment and Statefulset

---

charts/core/Chart.yaml
charts/core/templates/core-sts.yaml
charts/core/values.yaml
charts/horizon/Chart.yaml
charts/horizon/templates/ingest.yaml
charts/horizon/values.yaml
charts/soroban-rpc/Chart.yaml
charts/soroban-rpc/templates/soroban-rpc-sts.yaml
charts/soroban-rpc/values.yaml

The core, soroban rpc, and horizon ingest statefulsets do not require pods to come up in a specific order. Currently, the 1st pod in each of these statefulsets has to wait for the 0th pod to be ready in order for the 1st to initialize.
This PR adds a value in these helm charts with a default of `Parallel` allowing the 1st and 2nd and Nth pods to spin up concurrently
https://github.com/stellar/ops/issues/3861
https://github.com/stellar/ops/issues/3859
https://github.com/stellar/ops/issues/3858

Add parallel pod management to core, horizon ingest and rpc charts
