stellar/helm-charts

charts/horizon/Chart.yaml
charts/horizon/README.md
charts/horizon/templates/_core-config.tpl
charts/horizon/templates/_helpers.tpl
charts/horizon/templates/horizon-core-cm.yaml
charts/horizon/templates/horizon-ingest-cm.yaml
charts/horizon/templates/horizon-ingest-sts.yaml
charts/horizon/templates/horizon-web-cm.yaml
charts/horizon/templates/horizon-web-deployment.yaml
charts/horizon/values.yaml

Add initial version of the horizon helm chart
The chart is in early version but should be good enough for dev environments

Add horizon helm chart

---

charts/horizon/Chart.yaml
charts/horizon/templates/_core-config.tpl

remove wirex from list of validators
update Chart version
wirex has been removed from the pubnet tier 1 quorumset https://github.com/stellar/puppet-v4/pull/3059
simple change, no testing
https://github.com/stellar/ops/issues/2044

remove wirex and update Chart version

---

charts/friendbot/templates/friendbot01.yaml
charts/friendbot/values.yaml

rename network_passphrase and horizon_url
team agrees to use snake case
simple change, no need to test
N/A

rename network_passphrase and horizon_url

---

charts/soroban/Chart.yaml
charts/soroban/values.yaml

Signed-off-by: Satyam Zode <satyamz@users.noreply.github.com>

Add soroban core futurenet config

---

charts/horizon/templates/horizon-ingest-sts.yaml
charts/horizon/templates/horizon-ingress.yaml
charts/horizon/templates/horizon-web-deployment.yaml
charts/horizon/values.yaml

Add ingress support to the horizon chart
We want to have capability to expose horizon using Ingress

Add ingress support to the horizon chart

---

charts/stellar-network/Chart.yaml
charts/stellar-network/friendbot-subchart.yaml
charts/stellar-network/values.yaml

make friendbot a dependency of stellar-network
stellar-network is to be the parent chart
built manually
N/A

make friendbot a dependency of stellar-network

---

charts/stellar-network/templates/stellar-network-cm.yaml

update takeovernator and update_network
to wait until horizon and core are up before doing anything

update takeovernator and update_network

---

charts/friendbot/templates/friendbot01.yaml
charts/friendbot/values.yaml

change name of variable friendbot_seed to match what's being passed by stellar-network parent chart

change name of variable friendbot_seed

---

charts/soroban-rpc/templates/soroban-rpc-deployment.yaml

Signed-off-by: Satyam Zode <satyamz@users.noreply.github.com>

Fix domain for soroban-rpc endpoint

---

charts/core/templates/core-cm.yaml
charts/stellar-network/Chart.yaml
charts/stellar-network/templates/_helpers.tpl
charts/stellar-network/templates/stellar-network-cm.yaml
charts/stellar-network/templates/stellar-network-job.yaml
charts/stellar-network/values.yaml

* allows use of multiple history archives
* fixes if statement in upgrade_network.sh

use xdrpp image directly, bye bye takeovernator

---

charts/stellar-network/Chart.yaml

Signed-off-by: Satyam Zode <satyamz@users.noreply.github.com>

Rename soroban to soroban-rpc

---

charts/friendbot/templates/friendbot01.yaml
charts/friendbot/values.yaml

Friendbot horizonurl

---

charts/soroban-rpc/templates/soroban-rpc-deployment.yaml

Fix Ingress definition
In some cases template would not render

Fix Ingress definition

---

charts/friendbot/templates/friendbot01.yaml

fix name of key network_passphrase

fix name of key network_passphrase

---

charts/core/templates/core-cm.yaml

Fix core ConfigMap template
We can't quote some options

Fix core ConfigMap template

---

charts/soroban-rpc/templates/_helpers.tpl

Signed-off-by: Satyam Zode <satyamz@users.noreply.github.com>

Update horizon URL in soroban rpc

---

charts/horizon/Chart.yaml
charts/horizon/templates/horizon-ingest-cm.yaml

Improve horizon ConfigMap template
* allow CAPTIVE_CORE_USE_DB to be configured
* use official default for rate limiting
* add support for DISABLE_PATH_FINDING setting
* remove obsolete ENABLE_EXPERIMENTAL_INGESTION
This will make the chart more flexible

Improve horizon ConfigMap template

---

charts/horizon/Chart.yaml
charts/horizon/README.md
charts/horizon/templates/horizon-ingest-cm.yaml

horizon helm chart: add attributes to ingest-cm
add a few attributes, update Chart.yaml and README
needed by testnet production
has already been validated in testnet production
https://github.com/stellar/ops/issues/1510

horizon helm chart: add attributes to ingest-cm

---

README.md
charts/stellar-disbursement-platform/.helmignore
charts/stellar-disbursement-platform/Chart.yaml
charts/stellar-disbursement-platform/README.md
charts/stellar-disbursement-platform/templates/01.1-configmap-sdp.yaml
charts/stellar-disbursement-platform/templates/01.2-configmap-ap.yaml
charts/stellar-disbursement-platform/templates/01.3-configmap-tss.yaml
charts/stellar-disbursement-platform/templates/01.4-configmap-dashboard.yaml
charts/stellar-disbursement-platform/templates/02.1-deployment-sdp.yaml
charts/stellar-disbursement-platform/templates/02.2-deployment-ap.yaml
charts/stellar-disbursement-platform/templates/02.3-deployment-tss.yaml
charts/stellar-disbursement-platform/templates/02.4-deployment-dashboard.yaml
charts/stellar-disbursement-platform/templates/03.1-service-sdp.yaml
charts/stellar-disbursement-platform/templates/03.2-service-ap.yaml
charts/stellar-disbursement-platform/templates/03.3-service-dashboard.yaml
charts/stellar-disbursement-platform/templates/04.1-ingress-sdp.yaml
charts/stellar-disbursement-platform/templates/04.2-ingress-ap.yaml
charts/stellar-disbursement-platform/templates/04.3-ingress-dashboard.yaml
charts/stellar-disbursement-platform/templates/05.1-secrets-sdp.yaml
charts/stellar-disbursement-platform/templates/05.2-secrets-ap.yaml
charts/stellar-disbursement-platform/templates/05.3-secrets-tss.yaml
charts/stellar-disbursement-platform/templates/06-ephemeral-postgres.yaml
charts/stellar-disbursement-platform/templates/07-autoscaling.yaml
charts/stellar-disbursement-platform/templates/08-serviceaccount.yaml
charts/stellar-disbursement-platform/templates/NOTES.txt
charts/stellar-disbursement-platform/templates/_helpers.tpl
charts/stellar-disbursement-platform/templates/tests/test-connection.yaml
charts/stellar-disbursement-platform/values.yaml

Publishing the helm chart of Stellar Disbursement Platform. 
Original PR : https://github.com/stellar/stellar-disbursement-platform-backend/pull/9

feat: Publish stellar-disbursement-platform Helm Chart

---

README.md
charts/stellar-disbursement-platform/Chart.yaml

Follow-up to previous PR to add `stellar-disbursement-platform` chart. 
https://github.com/stellar/helm-charts/pull/60
* Cleaning up Chart.yaml 
* Fixing README link because it doesn't display properly 
Question for @mwtzzz @jacekn . Are V2 charts supported ?

SDP-663 Cleanup SDP chart

---

charts/stellar-disbursement-platform/Chart.yaml

Apparently helm package manager doesn't work with `-rc` .

SDP-663 Update SDP chart version

---

charts/stellar-disbursement-platform/Chart.yaml

Bump version of SDP helm chart
To keep it compliant with https://github.com/stellar/stellar-disbursement-platform-backend/pull/27

Bump version of SDP helm chart

---

charts/horizon/templates/_core-config.tpl

the bucketlistdb settings should help performance/catchup when core is config'd using on disk db.
relates to #64

include bucketlist db enable setting on captive core config

---

charts/soroban-rpc/testnet-values.yaml

fix the friendbot for testnet address.

fix friendbot for testnet

---

charts/stellar-disbursement-platform/Chart.yaml
charts/stellar-disbursement-platform/values.yaml

SDP helm chart release for the following updates: 
* SDP backend 2.1.1 https://github.com/stellar/stellar-disbursement-platform-backend/releases/tag/2.1.1

SDP release helm chart 2.1.2

---

charts/anchor-platform/sep-service/readme.md

Changed the SEP10_SIGNING_SEED and add comments to show these are examples to be less confusing

Changed the SEP10_SIGNING_SEED and add comments to show these are examples to be less confusing

---

charts/stellar-disbursement-platform/Chart.yaml
charts/stellar-disbursement-platform/templates/05.2-secrets-ap.yaml

- Fix the secrets in AnchorPlatform to use AP secrets.

Release 3.7.3
